Test

diff --git a/python/oliver_framework.egg-info/PKG-INFO b/python/oliver_framework.egg-info/PKG-INFO
--- a/python/oliver_framework.egg-info/PKG-INFO
+++ b/python/oliver_framework.egg-info/PKG-INFO
@@ -1,18 +1,127 @@
 Metadata-Version: 2.1
-Name: oliver_framework
-Version: 0.1
+Name: oliver-framework
+Version: 0.1.0
 Summary: Oliver Python Framework
 Home-page: https://github.com/oliverhuynh/oliver-framework
 Author: Oliver Huynh
-Author-email: oliver@jufist.com
-Requires-Dist: azure-storage-blob
-Requires-Dist: pyodbc
-Requires-Dist: python-dotenv
-Requires-Dist: schedule
-Requires-Dist: pydispatcher
-Requires-Dist: sqlalchemy
-Requires-Dist: colorlog
-Requires-Dist: pystray
-Requires-Dist: Pillow
-Requires-Dist: tk
-Requires-Dist: sqlparse
+Author-email: Oliver Huynh <oliver@jufist.com>
+License: MIT
+Requires-Python: >=3.8
+Description-Content-Type: text/markdown
+Requires-Dist: setuptools>=69.5.1
+
+# Oliver Framework
+
+## Setup
+
+- lib:
+  - Alpine: apk add --virtual build_deps gettext
+  - Debian: apt intall gettext
+- package.json
+
+```
+  "dependencies": {
+    "oliver-framework": "git@github.com:antbuddy-share/oliver-framework.git"
+  }
+```
+
+- `npm install`
+
+## Using bash structure exec
+
+```bash
+#!/bin/bash
+
+export YARNGLOBALDIR=${YARNGLOBALDIR:-"$(yarn global dir)"}
+globaldir=${YARNGLOBALDIR:-"$YARNGLOBALDIR"}
+if [[ -d "$globaldir/node_modules/oliver-framework" ]]; then
+  . "$globaldir/node_modules/oliver-framework/bash/common.sh"
+else
+  . $(dirname $(node -e "console.log('path: \'' + require.resolve('oliver-framework'))" | grep -F "path: '" | cut -d "'" -f 2))/bash/common.sh
+fi
+# If this is a script file
+. $OFSCRIPTPATH/includes/common.sh
+# If this is a source file
+# . $OFSOURCESCRIPTPATH/includes/common.sh
+
+exec--test() {
+  echo "Testing calls"
+}
+
+exec--main() {
+  local cmd=$(basename $0)
+  declare -F | grep exec-- | sed 's/declare -f exec/'$cmd' /'
+}
+
+vars_parse--add() {
+  FORMUSERNAME="$1"
+  FORMPWD="$2"
+}
+
+vars_verify--add() {
+  if [[ "$FORMUSERNAME" == "" || "$FORMPWD" == "" ]]; then
+    echo "[Error] Please verify your input data"
+    exit 1
+  fi
+}
+
+exec--add() {
+  echo "Main calls"
+  echo "$@"
+}
+
+oliver-common-exec --check-existed '$M0 $M1 $M2 $M3' "$@"
+```
+
+## Some more user cases
+
+```bash
+#!/bin/bash
+
+export YARNGLOBALDIR=${YARNGLOBALDIR:-"$(yarn global dir)"}
+globaldir=${YARNGLOBALDIR:-"$YARNGLOBALDIR"}
+
+# Optional
+shopt -s expand_aliases
+if [[ -d "$globaldir/node_modules/oliver-framework" ]]; then
+  . "$globaldir/node_modules/oliver-framework/bash/common.sh"
+else
+  . $(dirname $(node -e "console.log('path: \'' + require.resolve('oliver-framework'))" | grep -F "path: '" | cut -d "'" -f 2))/bash/common.sh
+fi
+# If this is a script file
+. $OFSCRIPTPATH/includes/common.sh
+# If this is a source file
+# . $OFSOURCESCRIPTPATH/includes/common.sh
+
+loadenv
+
+vars_parse--main() {
+  definedargs=("v|version*" "e|extra")
+  definedparams=("one", "two")
+  inputargs=("$@")
+  myargs inputargs definedargs definedparams
+  [[ "$?" != "0" ]] && return 1
+  set -- "${newargs[@]}"
+
+  RESTARGS=("$@")
+}
+
+exec--main() {
+  # Use rest parameters by RESTARGS instead of $@ normally here or override $@ by following command
+  set -- "${RESTARGS[@]}"
+  echo "Param: $MP_one"
+  echo "Arg version: $MA_version"
+  echo "Main"
+  exit
+}
+
+oliver-common-exec "$@"
+```
+
+# Using Docker Oliver Stack
+
+`. node_modules/oliver-framework/bash/oliverstack.sh` `oliver-stack --help`
+
+# Variables
+
+OLIVERDIR
